[package]
name = "vimanam"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "OpenAPI to Markdown documentation generator"
license = "MIT"
readme = "README.md"
repository = "https://github.com/nrynss/vimanam"

[dependencies]
# Command line argument parsing
clap = { version = "4.4", features = ["derive"] }

# JSON parsing
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging
log = "0.4"
env_logger = "0.10"

# Path operations
path-clean = "1.0"

[dev-dependencies]
# Testing
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.8"
